import { HttpException } from "@nestjs/common";

// The Phase 6 spec's required minimum error-code set (docs/SCHEMA_API_AUDIT.md §Phase 6
// pre-flight addendum) plus the generic HTTP-adjacent codes every module needs. Module-specific
// codes not listed here (e.g. commission/refund edge cases) are added as they're implemented,
// but must be added here — DomainException.code is typed against this union so a typo in a
// throw site fails at compile time instead of shipping an error the frontend can't map.
export type ErrorCode =
  | "VALIDATION_ERROR"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "CONFLICT"
  | "INVALID_CREDENTIALS"
  | "ACCOUNT_LOCKED"
  | "TOKEN_EXPIRED"
  | "TOKEN_REVOKED"
  | "EMAIL_TAKEN"
  | "PHONE_TAKEN"
  | "WEAK_PASSWORD"
  | "CREATOR_NOT_APPROVED"
  | "ALREADY_APPLIED"
  | "CAMPAIGN_FULL"
  | "REVIEW_REASON_REQUIRED"
  | "PROMO_NOT_FOUND"
  | "PROMO_EXPIRED"
  | "PROMO_NOT_STARTED"
  | "PROMO_INACTIVE"
  | "PROMO_USAGE_LIMIT"
  | "PROMO_CUSTOMER_LIMIT"
  | "PROMO_MINIMUM_NOT_REACHED"
  | "INVALID_OFFER"
  | "OFFER_INACTIVE"
  | "INVALID_ORDER_TRANSITION"
  | "INVALID_CAMPAIGN_TRANSITION"
  | "IDEMPOTENCY_KEY_REUSED"
  | "INSUFFICIENT_BALANCE"
  | "BELOW_MINIMUM"
  | "PAYOUT_ALREADY_RESERVED"
  | "ALREADY_FINALIZED"
  | "ALREADY_PAID"
  | "SLUG_TAKEN"
  | "SKU_TAKEN"
  | "PRODUCT_ARCHIVED"
  | "PRODUCT_NOT_ELIGIBLE"
  | "OFFER_ARCHIVED"
  | "INVALID_OFFER_TRANSITION"
  | "LANDING_ALREADY_EXISTS"
  | "LANDING_ARCHIVED"
  | "INVALID_LANDING_TRANSITION"
  | "CAMPAIGN_NOT_ELIGIBLE"
  | "CAMPAIGN_ARCHIVED"
  | "APPLICATION_NOT_ELIGIBLE"
  | "INVALID_APPLICATION_TRANSITION"
  | "INVALID_ONBOARDING_TRANSITION"
  | "INVALID_MEDIA_TYPE"
  | "MEDIA_TOO_LARGE"
  | "INVALID_MEDIA_DIMENSIONS"
  | "INVALID_MEDIA_DURATION"
  | "COVER_ALREADY_EXISTS"
  | "MEDIA_NOT_FOUND"
  | "PRODUCT_NOT_PHYSICAL"
  | "DELIVERY_REGION_NOT_FOUND"
  | "DELIVERY_REGION_UNAVAILABLE"
  | "REGION_REQUIRED"
  | "REFERRAL_CODE_INVALID"
  | "REFERRAL_SELF"
  | "REFERRAL_ALREADY_ATTRIBUTED"
  | "REFERRAL_NOT_FOUND"
  | "REFERRAL_RULE_INVALID"
  | "CONTENT_NOT_FOUND"
  | "CONTENT_NOT_ELIGIBLE"
  | "INVALID_CONTENT_TRANSITION"
  | "CONTENT_DEADLINE_PASSED"
  | "ATTACHMENT_REQUIRED"
  | "ATTACHMENT_NOT_FOUND"
  | "THUMBNAIL_ALREADY_EXISTS"
  | "TOO_MANY_ATTACHMENTS"
  | "OUT_OF_STOCK"
  | "CUSTOMER_INFO_INVALID"
  | "ORDER_NOT_FOUND"
  | "PAYMENT_NOT_FOUND"
  | "PAYMENT_ALREADY_PROCESSED"
  | "INVALID_PAYMENT_SIGNATURE"
  | "INVALID_PAYMENT_AMOUNT"
  | "PAYMENT_METHOD_NOT_SUPPORTED"
  | "REFUND_NOT_ELIGIBLE"
  | "COMMISSION_NOT_FOUND"
  | "INVALID_COMMISSION_TRANSITION"
  | "PAYOUT_NOT_FOUND"
  | "INVALID_PAYOUT_TRANSITION"
  | "PAYOUT_METHOD_NOT_FOUND"
  | "PAYOUT_METHOD_INACTIVE"
  | "NOTIFICATION_NOT_FOUND"
  | "NOTIFICATION_NOT_RETRYABLE"
  | "CANNOT_MODIFY_SELF"
  | "CANNOT_MODIFY_SYSTEM_ROLE"
  | "ROLE_ALREADY_ASSIGNED"
  | "ROLE_NOT_ASSIGNED"
  | "PERMISSION_ALREADY_ASSIGNED"
  | "PERMISSION_NOT_ASSIGNED"
  | "INVALID_REFUND_TRANSITION"
  | "INVALID_SETTING_VALUE"
  | "AI_NOT_CONFIGURED"
  | "AI_GENERATION_FAILED"
  | "INVALID_COMPETITION_TRANSITION"
  | "INVALID_AMOUNT"
  | "POST_URL_REQUIRED"
  | "BIO_COMPLIANCE_REQUIRED"
  | "STORAGE_ERROR"
  | "INVALID_STATE"
  | "INTERNAL_ERROR"
  | "TELEGRAM_NOT_CONFIGURED"
  | "INSTAGRAM_FETCH_FAILED"
  | "FIDEM_NOT_CONFIGURED"
  | "INVALID_FIDEM_SIGNATURE"
  | "INVALID_CLICK_TOKEN"
  | "FLOW_NOT_FOUND";

const STATUS_BY_CODE: Partial<Record<ErrorCode, number>> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_LOCKED: 403,
  TOKEN_EXPIRED: 401,
  TOKEN_REVOKED: 401,
  FORBIDDEN: 403,
  CREATOR_NOT_APPROVED: 403,
  NOT_FOUND: 404,
  PROMO_NOT_FOUND: 404,
  CONFLICT: 409,
  EMAIL_TAKEN: 409,
  PHONE_TAKEN: 409,
  ALREADY_APPLIED: 409,
  ALREADY_FINALIZED: 409,
  ALREADY_PAID: 409,
  IDEMPOTENCY_KEY_REUSED: 409,
  PAYOUT_ALREADY_RESERVED: 409,
  SLUG_TAKEN: 409,
  SKU_TAKEN: 409,
  PRODUCT_ARCHIVED: 409,
  PRODUCT_NOT_ELIGIBLE: 409,
  OFFER_ARCHIVED: 409,
  INVALID_OFFER_TRANSITION: 409,
  LANDING_ALREADY_EXISTS: 409,
  LANDING_ARCHIVED: 409,
  INVALID_LANDING_TRANSITION: 409,
  CAMPAIGN_NOT_ELIGIBLE: 409,
  CAMPAIGN_ARCHIVED: 409,
  CAMPAIGN_FULL: 409,
  INVALID_CAMPAIGN_TRANSITION: 409,
  APPLICATION_NOT_ELIGIBLE: 409,
  INVALID_APPLICATION_TRANSITION: 409,
  INVALID_ONBOARDING_TRANSITION: 409,
  INVALID_MEDIA_TYPE: 400,
  MEDIA_TOO_LARGE: 400,
  INVALID_MEDIA_DIMENSIONS: 400,
  INVALID_MEDIA_DURATION: 400,
  COVER_ALREADY_EXISTS: 409,
  MEDIA_NOT_FOUND: 404,
  PRODUCT_NOT_PHYSICAL: 409,
  DELIVERY_REGION_NOT_FOUND: 404,
  DELIVERY_REGION_UNAVAILABLE: 409,
  REGION_REQUIRED: 400,
  REFERRAL_CODE_INVALID: 400,
  REFERRAL_SELF: 409,
  REFERRAL_ALREADY_ATTRIBUTED: 409,
  REFERRAL_NOT_FOUND: 404,
  REFERRAL_RULE_INVALID: 400,
  CONTENT_NOT_FOUND: 404,
  CONTENT_NOT_ELIGIBLE: 409,
  INVALID_CONTENT_TRANSITION: 409,
  CONTENT_DEADLINE_PASSED: 409,
  ATTACHMENT_REQUIRED: 400,
  ATTACHMENT_NOT_FOUND: 404,
  THUMBNAIL_ALREADY_EXISTS: 409,
  TOO_MANY_ATTACHMENTS: 409,
  PROMO_EXPIRED: 409,
  PROMO_NOT_STARTED: 409,
  PROMO_INACTIVE: 409,
  PROMO_USAGE_LIMIT: 409,
  PROMO_CUSTOMER_LIMIT: 409,
  PROMO_MINIMUM_NOT_REACHED: 409,
  INVALID_OFFER: 400,
  OFFER_INACTIVE: 409,
  INVALID_ORDER_TRANSITION: 409,
  OUT_OF_STOCK: 409,
  CUSTOMER_INFO_INVALID: 400,
  ORDER_NOT_FOUND: 404,
  PAYMENT_NOT_FOUND: 404,
  PAYMENT_ALREADY_PROCESSED: 409,
  INVALID_PAYMENT_SIGNATURE: 400,
  INVALID_PAYMENT_AMOUNT: 400,
  PAYMENT_METHOD_NOT_SUPPORTED: 400,
  REFUND_NOT_ELIGIBLE: 409,
  INSUFFICIENT_BALANCE: 409,
  BELOW_MINIMUM: 400,
  COMMISSION_NOT_FOUND: 404,
  INVALID_COMMISSION_TRANSITION: 409,
  PAYOUT_NOT_FOUND: 404,
  INVALID_PAYOUT_TRANSITION: 409,
  PAYOUT_METHOD_NOT_FOUND: 404,
  PAYOUT_METHOD_INACTIVE: 409,
  NOTIFICATION_NOT_FOUND: 404,
  NOTIFICATION_NOT_RETRYABLE: 409,
  CANNOT_MODIFY_SELF: 409,
  CANNOT_MODIFY_SYSTEM_ROLE: 409,
  ROLE_ALREADY_ASSIGNED: 409,
  ROLE_NOT_ASSIGNED: 409,
  PERMISSION_ALREADY_ASSIGNED: 409,
  PERMISSION_NOT_ASSIGNED: 409,
  INVALID_REFUND_TRANSITION: 409,
  INVALID_SETTING_VALUE: 400,
  AI_NOT_CONFIGURED: 503,
  TELEGRAM_NOT_CONFIGURED: 503,
  // A best-effort external fetch failing (blocked, page changed, network) — 502, same "the
  // server-side dependency failed" precedent as AI_GENERATION_FAILED, not a client mistake.
  INSTAGRAM_FETCH_FAILED: 502,
  AI_GENERATION_FAILED: 502,
  INVALID_COMPETITION_TRANSITION: 409,
  INVALID_AMOUNT: 400,
  POST_URL_REQUIRED: 400,
  BIO_COMPLIANCE_REQUIRED: 403,
  // A genuine infra/adapter failure (e.g. StoragePort.put() rejecting), not a client mistake —
  // matches AI_GENERATION_FAILED's precedent of a 5xx for "the server-side dependency failed",
  // distinct from every other code above, which is 4xx because the client did something wrong.
  STORAGE_ERROR: 500,
  FIDEM_NOT_CONFIGURED: 503,
  INVALID_FIDEM_SIGNATURE: 400,
  INVALID_CLICK_TOKEN: 400,
  FLOW_NOT_FOUND: 404,
};

// The one exception type application/domain code should throw for business-rule failures —
// framework-level errors (Nest's own NotFoundException, ValidationPipe failures, etc.) are
// normalized into the same wire shape by AllExceptionsFilter, so callers never need to know
// which path produced an error.
export class DomainException extends HttpException {
  readonly code: ErrorCode;
  readonly details?: Record<string, unknown>;

  constructor(code: ErrorCode, message: string, details?: Record<string, unknown>) {
    super(message, STATUS_BY_CODE[code] ?? 400);
    this.code = code;
    this.details = details;
  }
}
